### ISSUE TITLE
Require tar file for aarch64 architecture

### ISSUE THREAD

**Issue by odidev** [aiortc/aiortc-codecs#4]
Hi Team,

I am working on adding aarch64 support in GHA for aiortc/aiortc package. It is fetching tar files from the releases of aiortc/aiortc-codecs package, but there is no tar file for aarch64 available in this. 

Do you have any plans to release a tar file for linux-aarch64?

It will be very helpful if aarch64 tar file is released. If any help is required in releasing it, I am happy to contribute.

**Comment by jlaine** [comment]
This was fixed in #3
